export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
//////////

export const ADD_SCHOOL_SUCCESS = "ADD_SCHOOL_SUCCESS";
export const ADD_SCHOOL_FAIL = "ADD_SCHOOL_FAIL";

export const GET_SCHOOL = "GET_SCHOOL";
export const GET_SCHOOL_SUCCESS = "GET_SCHOOL_SUCCESS";
export const GET_SCHOOL_FAIL = "GET_SCHOOL_FAIL";

export const GET_SCHOOL_BY_ID = "GET_SCHOOL_BY_ID";

/*export const TOGGLE_TRUE = "TOGGLE_TRUE";
export const TOGGLE_FALSE = "TOGGLE_FALSE";*/

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const GET_PROFILE = "USER_LOGIN";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "  GET_PROFILE_FAIL";

//////SEJOURS

export const GET_SEJOUR = "GET_SEJOUR";
export const GET_SEJOUR_SUCCESS = "GET_SEJOUR_SUCCESS";
export const GET_SEJOUR_FAIL = "GET_SEJOUR_FAIL";
export const GET_SEJOUR_BY_ID = "GET_SEJOUR_BY_ID";

export const ADD_SEJOUR_SUCCESS = "ADD_SEJOUR_SUCCESS";
export const ADD_SEJOUR_FAIL = "ADD_SEJOUR_FAIL";
export const ADD_NEWSLETTER = "ADD_NEWSLETTER";
export const ADD_NEWSLETTER_FAIL = "ADD_NEWSLETTER_FAIL";
export const ADD_CONTACT = "ADD_CONTACT";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";
export const ADD_DEVIS = "ADD_DEVIS";
export const ADD_DEVIS_FAIL = "ADD_DEVIS_FAIL";

export const GET_NEWSLETTER = "GET_NEWSLETTER";
export const GET_NEWSLETTER_SUCCESS = "GET_NEWSLETTER_SUCCESS";
export const GET_NEWSLETTER_FAIL = "GET_NEWSLETTER_FAIL";

export const GET_CONTACT = "GET_CONTACT";
export const LOG_OUT = "LOG_OUT";
export const TOKEN = "TOKEN";

export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAIL = "GET_CONTACT_FAIL";

export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAIL = "ADD_IMAGE_FAIL";
